package com.mmf.resumeBuilder.enums.skill;

import lombok.Getter;

@Getter
public enum SkillCategory {
    SOFTWARE_DEVELOPMENT(1),
    PROGRAMMING_LANGUAGES(2),
    NETWORK(4),
    HARDWARE(5),
    OPERATING_SYSTEMS(6),
    INDUSTRIAL_ENGINEERING(7),
    PROJECT_AND_PRODUCT_MANAGEMENT(8),
    MANAGEMENT(9),
    ELECTRICAL_ENGINEERING(10),
    MECHANICAL_AND_AEROSPACE_ENGINEERING(11),
    MINING_AND_MATERIALS_ENGINEERING(12),
    CIVIL_ENGINEERING(13),
    ARCHITECTURE_AND_URBAN_PLANNING(14),
    PETROLEUM_AND_POLYMER_CHEMICAL_ENGINEERING(15),
    ACCOUNTING_SOFTWARE(16),
    INSURANCE_FINANCIAL_SOFTWARE(17),
    STATISTICAL_SOFTWARE(18),
    DATABASE_MANAGEMENT(19),
    BIG_DATA_MINING_AND_BI(20),
    GAME(21);

    private int id;

    SkillCategory(int categoryId) {
        this.id = categoryId;
    }
}