package com.mmf.resumeBuilder.enums.hardskill;

public enum ChemicalEngineering  implements IHardSkillType {
    Aspen_MUSE,
    Aspen_HYSYS,
    Applied_Flow_Technology_Fathom,
    Aspen_Process_Manual,
    Aspen_plus,
    Aspen_PIMS,
    Aspen_OnLine,
    CMG,
    ChemOffice,
    ChemCad,
    Avocet,
    Economic_Evaluation,
    Eclips,
    Drilling_Office,
    COADE_PVElite,
    Geolog,
    Geoframe,
    Exchanger_Design_and_Rating,
    Exceed,
    IPM_Package,
    Invensys_SimSci_Esscor_PIPEPHASE,
    Hysis,
    Petrel,
    Operations_Support,
    Landmark_Package,
    Solid_vox,
    Process_Development,
    Pipesim,
    Petrol_Engineering,
    olga,
    Sysdrill;
}
