package com.mmf.resumeBuilder.enums.hardskill;

public enum MaterialsEngineering  implements HardSkillType {
    Dips,
    Datamine_Studio,
    ARCGIS,
    ARC_View,
    FLAC,
    ErmapperUDEC,
    ENVI,
    Downhole_Explorer,
    LOG_PLOT,
    Itasca_3DEC,
    GeoTechnical_Graphics,
    GEMS,
    PhaseP,
    Minex,
    MineSight,
    MineSched,
    LogMate,
    SLIDE,
    ROCLAB,
    Rockwork,
    Rock_Plane,
    Quick_Log,
    target,
    Swedge,
    Surpac,
    Surfer,
    Stereonet,
    Geosoft_Oasis_Montaj,
    Whittle,
    Vulcan;
}
