package com.mmf.resumeBuilder.enums;

public enum Country {
    AFGHANISTAN(1, IsoCode.AF),
    ALBANIA(2, IsoCode.AL),
    ALGERIA(3, IsoCode.DZ),
    ARGENTINA(4, IsoCode.AR),
    ARMENIA(5, IsoCode.AM),
    AUSTRALIA(6, IsoCode.AU),
    AUSTRIA(7, IsoCode.AT),
    AZERBAIJAN(8, IsoCode.AZ),
    BANGLADESH(9, IsoCode.BD),
    BELARUS(10, IsoCode.BY),
    BELGIUM(11, IsoCode.BE),
    BOSNIA_AND_HERZEGOVINA(12, IsoCode.BA),
    BRAZIL(13, IsoCode.BR),
    BULGARIA(14, IsoCode.BG),
    BURKINA_FASO(15, IsoCode.BF),
    CAMBODIA(16, IsoCode.KH),
    CAMEROON(17, IsoCode.CM),
    CANADA(18, IsoCode.CA),
    CHILE(19, IsoCode.CL),
    CHINA(20, IsoCode.CN),
    COLOMBIA(21, IsoCode.CO),
    COSTA_RICA(22, IsoCode.CR),
    CROATIA(23, IsoCode.HR),
    CUBA(24, IsoCode.CU),
    CZECH_REPUBLIC(25, IsoCode.CZ),
    DENMARK(26, IsoCode.DK),
    ECUADOR(27, IsoCode.EC),
    EGYPT(28, IsoCode.EG),
    ESTONIA(29, IsoCode.EE),
    FINLAND(30, IsoCode.FI),
    FRANCE(31, IsoCode.FR),
    GEORGIA(32, IsoCode.GE),
    GERMANY(33, IsoCode.DE),
    GREECE(34, IsoCode.GR),
    HONG_KONG(35, IsoCode.HK),
    HUNGARY(36, IsoCode.HU),
    ICELAND(37, IsoCode.IS),
    INDIA(38, IsoCode.IN),
    INDONESIA(39, IsoCode.ID),
    IRAN(40, IsoCode.IR),
    IRAQ(41, IsoCode.IQ),
    IRELAND(42, IsoCode.IE),
    ITALY(43, IsoCode.IT),
    JAPAN(44, IsoCode.JP),
    JORDAN(45, IsoCode.JO),
    KAZAKHSTAN(46, IsoCode.KZ),
    KUWAIT(47, IsoCode.KW),
    LIBYA(48, IsoCode.LY),
    MADAGASCAR(49, IsoCode.MG),
    MALAYSIA(50, IsoCode.MY),
    MEXICO(51, IsoCode.MX),
    MOROCCO(52, IsoCode.MA),
    NETHERLANDS(53, IsoCode.NL),
    NIGERIA(54, IsoCode.NG),
    NORWAY(55, IsoCode.NO),
    OMAN(56, IsoCode.OM),
    PAKISTAN(57, IsoCode.PK),
    PHILIPPINES(58, IsoCode.PH),
    POLAND(59, IsoCode.PL),
    PORTUGAL(60, IsoCode.PT),
    QATAR(61, IsoCode.QA),
    ROMANIA(62, IsoCode.RO),
    SAUDI_ARABIA(63, IsoCode.SA),
    SENEGAL(64, IsoCode.SN),
    SERBIA(65, IsoCode.RS),
    SINGAPORE(66, IsoCode.SG),
    SLOVAKIA(67, IsoCode.SK),
    SLOVENIA(68, IsoCode.SI),
    SOUTH_AFRICA(69, IsoCode.ZA),
    SPAIN(70, IsoCode.ES),
    SRI_LANKA(71, IsoCode.LK),
    SWEDEN(72, IsoCode.SE),
    SWITZERLAND(73, IsoCode.CH),
    TAJIKISTAN(74, IsoCode.TJ),
    THAILAND(75, IsoCode.TH),
    TUNISIA(76, IsoCode.TN),
    TURKEY(77, IsoCode.TR),
    TURKMENISTAN(78, IsoCode.TM),
    UKRAINE(79, IsoCode.UA),
    UNITED_ARAB_EMIRATES(80, IsoCode.AE),
    UNITED_KINGDOM(81, IsoCode.GB),
    UNITED_STATES(82, IsoCode.US),
    UZBEKISTAN(83, IsoCode.UZ),
    VIET_NAM(84, IsoCode.VN),
    YEMEN(85, IsoCode.YE),
    RUSSIA(86, IsoCode.RU),
    PALESTINE(87, IsoCode.PS),
    SYRIA(88, IsoCode.SY);

    private final int id;
    private IsoCode isoCode;

    Country(int id, IsoCode isoCode) {
        this.id = id;
    }
}
